server:
  port: 8888
spring:
  application:
    name: adventureworks-configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/FlaviaPP/bootcamp-adventureworks-configserver-repo.git
          default-label: main